version: '3.8'

services:
  app:
    build: ./
    command: ./app
    depends_on:
      - redis
    environment:
      REDIS_HOST: "redis"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: always